variables:
  - group: vm_creds

trigger:
  - master
  
pool:
      vmImage: ubuntu-latest
    # Don't run against PRs
   
stages :
  - stage: validate
    jobs:
    - job: validate
      continueOnError: false
      steps:
      - task: TerraformInstaller@0
        displayName: 'install'
        inputs:
          terraformVersion: '0.13.4'
      - task: TerraformTaskV1@0
        displayName: 'init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'SP1'
          backendAzureRmResourceGroupName: 'terraformsf'
          backendAzureRmStorageAccountName: 'storagestprd001'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'dev.tfstate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'
      - task: TerraformTaskV1@0
        displayName: 'validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'
           
  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
      - job: terraform_plan
        steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '0.13.4'
              - task: TerraformTaskV1@0
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'SP1'
                  backendAzureRmResourceGroupName: 'terraformsf'
                  backendAzureRmStorageAccountName: 'storagestprd001'
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'dev.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'
              - task: TerraformTaskV1@0
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  commandOptions: -input=false -var "admin_password=$(admin_password)"
                  environmentServiceNameAzureRM: 'SP1'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'
 
  - stage: apply
    dependsOn: [plan]
    condition: succeeded('plan')
    jobs: 
    - job: terraform_apply
      steps:
              - checkout: self
              - task: TerraformInstaller@0
                displayName: 'install'
                inputs:
                  terraformVersion: '0.13.4'
              - task: TerraformTaskV1@0
                displayName: 'init'
                inputs:
                  provider: 'azurerm'
                  command: 'init'
                  backendServiceArm: 'SP1'
                  backendAzureRmResourceGroupName: 'terraformsf'
                  backendAzureRmStorageAccountName: 'storagestprd001'
                  backendAzureRmContainerName: 'tfstate'
                  backendAzureRmKey: 'dev.tfstate'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'
              - task: TerraformTaskV1@0
                displayName: 'plan'
                inputs:
                  provider: 'azurerm'
                  command: 'plan'
                  commandOptions: -input=false -var "admin_password=$(admin_password)"
                  environmentServiceNameAzureRM: 'SP1'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'
              - task: TerraformTaskV1@0
                displayName: 'apply'
                inputs:
                  provider: 'azurerm'
                  command: 'apply'
                  commandOptions: -input=false -var "admin_password=$(admin_password)"
                  environmentServiceNameAzureRM: 'SP1'
                  workingDirectory: '$(System.DefaultWorkingDirectory)/WindowsVM/'